// <auto-generated />
using System;
using HealthStory.Web.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HealthStory.Web.Migrations
{
    [DbContext(typeof(HealthStoryContext))]
    partial class HealthStoryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("HealthStory.Web.Entities.AppUser", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("Login");

                    b.Property<string>("Password");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("HealthStory.Web.Entities.BloodTest", b =>
                {
                    b.Property<int>("BloodTestId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Date");

                    b.Property<int?>("UserId");

                    b.HasKey("BloodTestId");

                    b.HasIndex("UserId");

                    b.ToTable("BloodTests");
                });

            modelBuilder.Entity("HealthStory.Web.Entities.BloodTestSubstance", b =>
                {
                    b.Property<int>("BloodTestSubstanceId")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("BloodTestId");

                    b.Property<int?>("SubDefId");

                    b.Property<int>("Value");

                    b.HasKey("BloodTestSubstanceId");

                    b.HasIndex("BloodTestId");

                    b.HasIndex("SubDefId");

                    b.ToTable("BloodTestsSubstances");
                });

            modelBuilder.Entity("HealthStory.Web.Entities.SubDef", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Max");

                    b.Property<int>("Min");

                    b.Property<string>("Name");

                    b.Property<string>("Unit");

                    b.HasKey("Id");

                    b.ToTable("SubDefs");
                });

            modelBuilder.Entity("HealthStory.Web.Entities.BloodTest", b =>
                {
                    b.HasOne("HealthStory.Web.Entities.AppUser", "AppUser")
                        .WithMany("BloodTests")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("HealthStory.Web.Entities.BloodTestSubstance", b =>
                {
                    b.HasOne("HealthStory.Web.Entities.BloodTest", "BloodTest")
                        .WithMany("BloodTestSubstances")
                        .HasForeignKey("BloodTestId");

                    b.HasOne("HealthStory.Web.Entities.SubDef", "SubDef")
                        .WithMany("BloodTestSubstances")
                        .HasForeignKey("SubDefId");
                });
#pragma warning restore 612, 618
        }
    }
}
